apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: metallb-operator
  namespace: metallb-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator-sub
  namespace: metallb-system
spec:
  channel: ${CHANNEL_NAME}
  installPlanApproval: "Manual"
  name: metallb-operator
  source:  ${CATALOG_SOURCE_NAME}
  sourceNamespace: openshift-marketplace
