apiVersion: v1
kind: Namespace
metadata:
  name: node-health-check
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: node-health-check-operator
  namespace: node-health-check
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-health-check-operator
  namespace: node-health-check 
spec:
  channel: ${CHANNEL_NAME}
  installPlanApproval: Manual 
  name: node-healthcheck-operator
  source: ${CATALOG_SOURCE_NAME}
  sourceNamespace: openshift-marketplace
  package: node-healthcheck-operator


