apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: node-health-check-operator
  namespace: openshift-operators
spec:
  channel: ${CHANNEL_NAME}
  installPlanApproval: Manual 
  name: node-healthcheck-operator
  source: ${CATALOG_SOURCE_NAME}
  sourceNamespace: openshift-marketplace
  package: node-healthcheck-operator


