apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
spec:
  size: 1x.extra-small
  storageClassName: ${STORAGE_CLASS_NAME}
  storage:
    secret:
      name: ${BUCKET_NAME}-credentials
      type: s3
  tenants:
    mode: openshift-logging    
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  visualization:
    type: ocp-console
  logStore:
    type: lokistack
    lokistack:
      name: logging-loki
  collection:
    type: vector
---
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  pipelines: 
  - name: all-to-default
    inputRefs:
    - infrastructure
    - application
    - audit
    outputRefs:
    - default
