apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: localfs
  namespace: openshift-local-storage
spec:
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - key: cluster.ocs.openshift.io/openshift-storage
            operator: In
            values:
              - ""
  storageClassName: localfs
  volumeMode: Filesystem
  fsType: ${FSTYPE}
  maxDeviceCount: 10 # optional, limit devices provisioned per node
  deviceInclusionSpec:
    deviceTypes: # list of types to allow
      - disk
    deviceMechanicalProperty:
      - NonRotational
    minSize: 1Gi # optional, minimum size of device to allow
    maxSize: 10Ti # optional, maximum size of device to allow
